import { type Response } from "express";
import { geminiService } from "../../services/ai/gemini.service.js";
import prisma from "../../utils/prisma.js";
import { success, created, AppError, HttpStatus, ErrorCode } from "../../utils/response.js";

export const autoCvController = {
  async generate(req: any, res: Response) {
    try {
      const { jobDescription } = req.body;
      const userId = req.user.id;

      // 1. Get User Profile
      const profile = await prisma.userProfileData.findUnique({
        where: { userId }
      });

      if (!profile) {
        throw new AppError("Please complete your profile first", HttpStatus.BAD_REQUEST, ErrorCode.VALIDATION_ERROR);
      }

      // 2. Scrape Job Data and Generate tailored content
      const [jobData, tailoredContent] = await Promise.all([
        geminiService.scrapeJobData(jobDescription),
        geminiService.generateTailoredDocs(profile.content, jobDescription)
      ]);

      return success(res, "Generated tailored content successfully", HttpStatus.OK, {
        jobData,
        tailoredContent
      });
    } catch (error) {
      throw error;
    }
  },

  async save(req: any, res: Response) {
    try {
      const userId = req.user.id;
      const { jobData, tailoredContent } = req.body;

      // 1. Create Job Application
      const application = await prisma.jobApplication.create({
        data: {
          userId,
          company: jobData.company,
          jobTitle: jobData.jobTitle,
          location: jobData.location,
          salaryMin: jobData.salaryMin,
          salaryMax: jobData.salaryMax,
          applicationStatus: "SAVED",
          notes: "Auto-generated via AI"
        }
      });

      // 2. Create Resume (Tailored)
      const resume = await prisma.resume.create({
        data: {
          userId,
          name: `Tailored CV - ${jobData.company}`,
          type: "RESUME",
          content: tailoredContent.resumeContent,
          settings: (tailoredContent.resumeContent as any).settings || {},
          isAutoGenerated: true
        }
      });

      // 3. Create Cover Letter
      const coverLetter = await prisma.resume.create({
        data: {
          userId,
          name: `Tailored Cover Letter - ${jobData.company}`,
          type: "COVER_LETTER",
          content: { body: tailoredContent.coverLetter },
          settings: {},
          isAutoGenerated: true
        }
      });

      // 4. Link documents to application
      await prisma.applicationResume.createMany({
        data: [
          { applicationId: application.id, resumeId: resume.id },
          { applicationId: application.id, resumeId: coverLetter.id }
        ]
      });

      return success(res, "Application and tailored documents saved successfully", HttpStatus.CREATED, { application, resume, coverLetter });
    } catch (error) {
      throw error;
    }
  }
};
